apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: us-west-2
  
nodeGroups:
  - name: ng-1
    instanceType: m5.large
    minSize: 0
    maxSize: 3
    desiredCapacity: 2    
    labels:
      lifecycle: OnDemand
      intent: control-apps
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        albIngress: true
    ssh: # use existing EC2 key
      publicKeyName: eksworkshop